### ISSUE TITLE
Criar desconto na OS

### ISSUE THREAD

**Issue by leocampbel** [TecSecret/TSDC-Assistencia#1]
Olá, como vcs pegaram o projeto, e até agora ninguém conseguiu fazer um desconto na OS, gostaria que vcs tentassem faze-lo.

**Comment by TecSecret** [comment]
Boa noite @leocampbel ,

Obrigado pela sugestão.

De mais detalhes, como por exemplo como seria esses desconto, em que parte da OS seria o desconto, em que momento seria aplicado o desconto, como seria aplicado, etc. pois assim podemos analisar a melhor forma de implementação e se será ou não implantado.
Abraços

**Comment by leocampbel** [comment]
Bom dia!
Obrigado pelo interesse em querer criar essa solução!

Depois que se cria uma OS, tem como colocar os produtos e serviços, poderia der uma outra aba chamada "financeiro" que nela teria que conter os valor total de serviço e o valor total de produtos e um campo para dar desconto ou em Reais ou em porcentagem, e  no final o valor total da OS. ai na tela de impressão poderia estar essas campos lá também.
Compreendeu?

Obrigado!

**Comment by darouca** [comment]
Olá, será que é necessário outra aba mesmo?
Talvez colocar um campo no serviço e produtos, depois do subtotal. Um campo que possamos colocar o valor do desconto.

Quando visualizamos a OS, ele soma os produtos com serviços, desconta o valor que colocamos lá e mostra o Valor total. Não fica mais simples?

**Comment by leocampbel** [comment]
Olá @darouca.
Pode ser na mesma aba.
Poderia calcular o valor total na mesma tela sem der que abrir a tela de impressão.
Mas isso fica ao critério de vocês, eu já tentei acrescentar e não tive sucesso em nada.
Boa programação!

**Comment by darouca** [comment]
Também não obtive sucesso em meus testes.

**Comment by dcweb-solutions** [comment]
Olá, @leocampbel e @darouca, nós arrumamos o desconto que já estava sendo feita pela equipe "mapos", assim deixando o desconto na aba produtos e serviços. E será exibida no visualizar OS.

**Comment by darouca** [comment]
Isso já foi implantado quando subiram o código ou será enviado? Fiquei na dúvida. Obrigado.

**Comment by dcweb-solutions** [comment]
Ainda hoje iremos subir um repositório atualizado, com diversas correções internas. Novos campos na OS e e correções para uso com SSL.

**Comment by darouca** [comment]
Show de bola...

**Comment by TecSecret** [comment]
Boa noite, versão publicada com muitas funções e recursos., 

Solicitação atendida no commit #v1.0_final

**Comment by TecSecret** [comment]
Boa noite,

Novas atualizações e versão no  **[Release](https://github.com/TecSecret/TSDC-Assistencia/releases/tag/v1.0_final)** lançado hoje.


A TecSecret e a DC WEb Solution desejo um bom uso do sistema a todos.
