### ISSUE TITLE
Area do cliente para consultar OS

### ISSUE THREAD

**Issue by feralton** [TecSecret/TSDC-Assistencia#10]
Ola desenvolvedores, boa tarde. Primeiramente gostaria de mais uma vez agradecer a TecSecret juntamente com a @dcweb-solutions por estar dando "vida" ao sistema.

Gostaria de fazer algumas sugestões com relação ao sistema, mais especificamente na área do cliente para consulta da OS sendo:
- Na area do cliente, as informações de cadastro (Minha Conta) ser exibido apenas em modo leitura para forçar o cliente a ligar para nós realizarmos a atualização do seu cadastro;
- Ao invés de ser gerado um código para o acesso do cliente, se seria possível o cliente logar no sistema usando seu email como usuários e seu cpf (já que cpf é obrigatório do cadastro do cliente, todos terão), ao inves de um código, pois são duas informações que o cliente tem conhecimento, tornando mais simples o acesso.
- Um checkbox para habilitar ou não a área de vendas (sinceramente não sei se o cliente precisa dessa área pois o grande objetivo dessa área é tornar mais dinâmico o acesso a informação do status da OS) ou até mesmo remover essa área pois muitas vezes nós realizamos venda utilizando usuário padrão (EX: Consumidor) para agilizar o processo de vendas.

Agora na área de OS, um campo para pesquisa pelo numero da OS, para ficar mais rápido o processo de alteração ou finalização da OS.

Muito obrigado pessoal pela iniciativa.
Um grande abraço.
Fernando Silva

**Comment by TecSecret** [comment]
Boa tarde @feralton ,

Primeiramente obrigado pelas suas sugestões.

Nós e a @dcweb-solutions  optamos por não deixar a opção de login com e-mail + CPF devido a ser dados de fácil acesso hoje na internet, sendo assim poderia expor dados atualizados do cliente indevidamente. Por isso deste código, caso você deseja pode preencher sem problemas no campo código o nº do cpf do seu cliente, vai de você internamente definir qual será o tipo de código padrão.

Quando as suas outras sugestões vamos analisar internamente e se as mesmas forem aceitas, serão aplicadas em commit futuros, ou caso precise de mais detalhes será solicitado por aqui também.

Quanto a pesquisa de OS, na área admin o sistema possui uma pesquisa, e se você digitar o número da OS no campo de pesquisa no canto superior direito do sistema o mesmo já retorna. veja nas imagens:
![image](https://cloud.githubusercontent.com/assets/6561517/24523242/c82a97dc-1568-11e7-8f8a-f8afc2483503.png) , caso não seja isso me corrija por favor.

Um grande abraço

**Comment by feralton** [comment]
Ola bom dia. 

Deu certo a pesquisa. Era bem isso que estava precisando e já estamos utilizando por aqui.

Muito obrigado equipe de desenvolvimento.

**Comment by dcweb-solutions** [comment]
Olá @feralton 

Que bom, caso tenha mais alguma sugestão ou relato de algum erro, nos informe. 

Obrigado!

**Comment by feralton** [comment]
Obrigado. 

Tenho algumas sugestões sim, pois acredito muito nesse sistema, e vou postando por tópico para facilitar o mapeamento.

[]s

**Comment by TecSecret** [comment]
@feralton  Boa Tarde,

Para não haver mistura de assuntos, cada idéia sua abra um novo commit para ser debatido entre todos os participantes a idéia. 

Obrigado e bom uso, acompanhe as atualizações em nosso git.

Abraços
