### ISSUE TITLE
como consigo o codigo da area do cliente

### ISSUE THREAD

**Issue by Ironaldo-Silva** [TecSecret/TSDC-Assistencia#12]
olá amigos! por gentileza como consigo o codigo da area do cliente?

**Comment by TecSecret** [comment]
Boa noite @Ironaldo-Silva, 

Este código é você quem escolhe qual você vai adicionar e também o padrão que deseja usar e passar para seu cliente. 

Ex.: Você pode adicionar o número rg do cliente, o telefone do mesmo, colocar o nome do meio do cliente, o nome da sua empresa etc.

 Importante você informar para seu cliente este valor para ele ter acesso a área do cliente e acompanhar o andamento da OS.

Um grande abraço.

**Comment by Ironaldo-Silva** [comment]
Bom dia, ok essa parte eu entendi, mas como o cliente irar acessar essa informação? Em algum site eu tenho um site ele entraria no site e ia em ferificar os mas teia o código pra ele conseguir acesso a os, como ele acessa a informação da os dele?

**Comment by Ironaldo-Silva** [comment]
Eu gosto muito desse programa de os, parabéns por continuar deixando ele perfeito pra assistência técnica, vcs estão de parabéns, sou técnico em informática e preciso muito de um sistema de OS ate agora esse me parece bem especifico para assistência técnica. Muito show o programa. Aproveitando minha opinião se conseguir melhorar a parte de imprimir os pois não sai as tabelas era bom separar informações por tabelas tipo deixar as bordas separando as informações e o que couber em uma linha manter na mesma linha tipo  modelo, serie, e tipo etc ok o reto ta filé demais. E se tiver como o cliente acessar so site da assistência  status da os seria maravilhoso . Grande abraço a todos

**Comment by Fcodapaz** [comment]
@Ironaldo-Silva pra acessar a área do cliente é só colocar "/conecte" depois do domínio.
ex:  http://127.0.0.1/sistema/conecte

**Comment by Ironaldo-Silva** [comment]
Muito obrigado, show
