### ISSUE TITLE
Remover campos obrigatorios

### ISSUE THREAD

**Issue by leocampbel** [TecSecret/TSDC-Assistencia#13]
Olá, instalei o sistema no meu servidor, parabéns, esta bem melhor, vcs fizeram muitas alterações otimas, até esconderam os endereços de URL, parabéns.

Gostaria de deixar uma solicitação de remoção de alguns campos obrigatórios que não há necessidade de der, segue elas:

No cadastro de cliente:
Sugiro deixar como campos obrigatórios o nome e email
O ultimo campo não esta a descrição do que solicita.

Ordem de serviço:
poderia retirar os campos obrigatório de:
Fabricante, modelo e tipo de equipamento

Dados do emitente:
a IE nao é necessária, pois minha empresa não tem assim como varias

Acho que é isso.

Obrigado!

**Comment by dcweb-solutions** [comment]
Olá @leocampbel, agradecemos pelo elogio. Nós iremos avaliar essas sugestões, alguns erros já está sendo corrigidos como no caso do campo sem descrição. 

Obrigado!

**Comment by SmithRider** [comment]
leocampbel, No meu removi alguns campos obrigatórios.
