### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by kalukramer** [TecSecret/TSDC-Assistencia#2]
When I try to make update from old version give this error:
An uncaught Exception was encountered

Type: Exception

Message: Configured database connection is persistent. Aborting.

Filename: /home/teconlin/public_html/rma01/system/libraries/Session/drivers/Session_database_driver.php

Line Number: 94

**Comment by TecSecret** [comment]
Boa tarde, para realizar o update para a nossa versão, realiza um backup do sistema e banco de dados e baixe o repositório aqui apresentado.
Após apague ou renemear as pastas abaixo:
application
System
vendor
assets/css
assets/font-awesome
assets/js

Após mova todos os arquivos baixado para o root do seu domínio.

Após altere o nome dos arquivos em application/config config.php_new para config.php e adicione as informações conforme apresentado no procedimento de instalação e faça o mesmo com o arquivo database.php_new.

Importante lembrar que nos modificamos e ajustamos o sistema utilizando o mysql 5.7 e o php 7 em hospedagens com Cpanel e Plesk.

Qualquer dúvida estamos a disposição.

**Comment by kalukramer** [comment]
Não tenho essas versões:
cPanel Version 	62.0 (build 17)
Apache Version 	2.2.31
Versão de PHP 	5.4.45
MySQL Version 	5.5.54-cll
Architecture     	x86_64
Operating System 	linux

Inicialmente o log cliente tinha um problema no "sort" das OS, aparecem da menor para a maior, ainde se mantem assim? no acesso do backofice as OS aparecem em sentido decrecente, como deve ser mas no cliente aparece no sentido crescente.

**Comment by kalukramer** [comment]
Estive a analisar o vosso código e o acesso ao "conecte" cliente não existe, é optimo o cliente conultar o estado das OS, evita telefonemas e e-mails... na versão antiga que tenho em funcionamento tem esse acesso ativo, só o sort não funciona.

**Comment by TecSecret** [comment]
@kalukramer Bom dia, 

Acredito que funcione normalmente com as especificações acima, como informado testamos e sempre vamos trabalhar em cima de tecnologias mais recentes, por isso já usamos o PHP7 e MySQL 5.7.
Quanto a versão do seu php, basta alterar a mesma no php selector do cpanel, no mysql não influencia pois o 5.5 suporta InnoDB. Importante também no seu php.ini deixar a opção session.save_path = /var/lib/php/sessions   e open_basedir = none. Isso evita muitos erros

Se você puder enviar, em resposta aqui no git mesmo a versão que você tem ai para nos analisarmos, seria útil, pois essa área do cliente que você fala não achamos a mesma no projeto original Mapos. E ai podemos realizar os ajustes e implantar este acesso para todos.

Juntos podemos transformar o melhor sistema para Assistências Técnicas.

**Comment by kalukramer** [comment]
Terei o maximo prezer em partilhar todo o software que tenho incluido todas as modificações que fui intruduzindo, era optimo eu explicar primeiro, pode ser via skype? vou enviar um e-mail....

**Comment by TecSecret** [comment]
Boa tarde @kalukramer ,

Nova release postada release. [Clique Aqui](https://github.com/TecSecret/TSDC-Assistencia/releases/tag/v1.1) a mesma possui o código disponibilizada por você e mais umas alterações.

Provavelmente vai resolver o seu problema. Lembro que a listagem correta das OS só acontece quando o cliente clica em Ordem de serviço, não no painel. No painel vai ser implementado ainda.
