### ISSUE TITLE
Ajuda, como baixar só os arquivos modificados

### ISSUE THREAD

**Issue by leocampbel** [TecSecret/TSDC-Assistencia#20]
Olá pessoal, me desculpe a ignorância, mas eu não sei como eu consigo só baixar as alterações dos comits para poder atualizar os arquivos no meu servidor, a unica maneira  que eu sei e baixando um zip de tudo, teria como baixar só os arquivos modificados de cada comit?

Desculpem a falta de conhecimento no Github.

**Comment by TecSecret** [comment]
@leocampbel, boa noite,

Basta você acessar o commit que você deseja e depois fazer o download dos arquivos do mesmo.

Abraços e qualquer dúvida estamos a disposição.
