### ISSUE TITLE
Lançamento não exibe na área Financeiro

### ISSUE THREAD

**Issue by guhfalcao01** [TecSecret/TSDC-Assistencia#3]
Lançamento não exibe na área Financeiro apenas no meu database, por mais que atualize ele nao exibe.
Porem em minha database consta tudo direitinho.
No lançamento do "site" só aparece Nenhuma lançamento encontrado.
Oque poderia está ocorrendo?Com a versão antiga do projeto original mapos eu tinha o mesmo problema.

Desde já agradeço!

**Comment by dcweb-solutions** [comment]
Olá @guhfalcao01,

Isso ocorre porque ele filtra por data, quando for o dia dessa receita ou despesa, ele irá aparecer.
Ou você pode estar filtrando manualmente para ver esse lançamento. Basta colocar a data inicial e final. 

Aguardamos o seu retorno!

**Comment by guhfalcao01** [comment]
Ok. Entendi...

Muito obrigado, nao estava entendendo a funcionalidade e achei que seria um problema. Peço desculpas pela leiguice .

**Comment by dcweb-solutions** [comment]
Imagina, qualquer outro problema nos reporte.

Abraços!
