### ISSUE TITLE
Instalacao

### ISSUE THREAD

**Issue by manuelnice** [TecSecret/TSDC-Assistencia#32]
Axo que o sistema está bastante interessante, só e pena que obrigue a ser instado em Roots directo, quando o mesmo deveria ser possível instalar em sub pasta ou como sub domínio, pois quando uma empresa tem o seu website e pretende usar a assistência numa sub pasta ou num sub domínio.

**Comment by TecSecret** [comment]
Bom dia @manuelnice 
Na próxima versão o mesmo terá um auto instalador, vai ficar tudo mais fácil.

Um grande abraço

**Comment by manuelnice** [comment]
obrigado
