### ISSUE TITLE
Editar o titulo na guia do navegador?

### ISSUE THREAD

**Issue by guhfalcao01** [TecSecret/TSDC-Assistencia#4]
Qual arquivo eu edito pra mudar aquele nome que fica na guia do navegador? Já tentei de tudo mais parece que ele é um arquivo dentro da **Index.hp**

**Se possível claro!**

Desculpa a leiguice, sou novo em PHP .

**Comment by TecSecret** [comment]
@guhfalcao01 Boa noite,

Assim que a internacionalização do sistema estiver concluída você vai poder editar o mesmo nos arquivos de tradução. No momento ainda não é possível, pois não está finalizada a implantação multi-idiomas. Provavelmente em uma das 2 próximas releases você vai poder fazer isso.

Um grande abraço

**Comment by darouca** [comment]
São dois arquivos. Um na tela de login, outro após o login. São eles:
/application/views/mapos/login.php
/application/views/tema/topo.php

Abraços

**Comment by TecSecret** [comment]
Boa noite @darouca ,

Informo que a versão que está em nosso git usa outra forma de arquitetura diferente um pouco da utilizada no projeto original mapos, pois nós realizamos certas adaptações para as tecnologias mais recentes, em caso de dúvida reabra o Issues, pois Issues fechados dificilmente são monitorados pela equipe da TecSecret e @dcweb-solutions .
Um grande abraço
