### ISSUE TITLE
Tem como usar localmente

### ISSUE THREAD

**Issue by Fcodapaz** [TecSecret/TSDC-Assistencia#5]
Tem como usar localmente com apache?
por que não estou conseguindo.

**Comment by TecSecret** [comment]
Bom dia @Fcodapaz 

Sim pode usar normalmente desde que esteja dentro dos pré-requisitos apresentado na Wiki, inclusive nossos testes são feitos localmente inicialmente, depois em hospedagens Plesk e Cpanel.

Mas se puder descrever melhor o erro que acontece agradecemos.

Lembre-se quanto mais informações, melhor.

Um abraço

**Comment by Fcodapaz** [comment]
Sim,esta dentro dos pre-requistos.
Primeiro depois de editar arquivo confi.phb_new e database.php_new 
aparece isso: The configuration file does not exist.
renomeei os arquivo conf e database tirando o '_new'.
ai a pagina vai para http://os.dev/login
e aparece isso:
 Não é possível acessar esse site
Esse site na intranet da empresa, organização ou escola tem o mesmo URL de um website externo. 
Tente entrar em contato com o administrador do sistema.
ERR_ICANN_NAME_COLLISION
Tem alguma ideia do que seja?

**Comment by TecSecret** [comment]
Boa tarde @Fcodapaz ,

Nova release postada release. [Clique Aqui](https://github.com/TecSecret/TSDC-Assistencia/releases/tag/v1.1) a mesma possui diversas correções e mais umas alterações.

Atualize a mesma ou realiza a atualização limpa da mesma.

Qualquer coisa estamos a disposição. 
Um grande abraço.

**Comment by Fcodapaz** [comment]
continuo com o mesmo erro.
