### ISSUE TITLE
erro v1.1

### ISSUE THREAD

**Issue by Fcodapaz** [TecSecret/TSDC-Assistencia#6]
Continuo com o mesmo erro mesmo após atualização na versao 1.1..
tem alguma ideia do que seja?

**Comment by TecSecret** [comment]
Qual erro, descreva  mesmo por favor @Fcodapaz

**Comment by Fcodapaz** [comment]
Depois que coloco login e senha, que entro na pagina principal do sistema aparece uma janela assim
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

fecho a janela e onde eu cliko dar erro...clientes, produtos, financeiro sempre aparece isso:
exemplo: http://127.0.0.1/sistema/financeiro/lancamentos
404 Page Not Found
The page you requested was not found.

**Comment by TecSecret** [comment]
Bom dia @Fcodapaz 
Este problema é devido a alguma biblioteca ou arquivo não adicionado corretamente ou até mesmo algo no PHP faltando. 

Sugiro que realize um update para a nossa nova release  **[Clique Aqui](https://github.com/TecSecret/TSDC-Assistencia/releases/tag/v1.1_update_1)**.
Importante ela corrige alguns erros de string e 404.


Caso o problema persista nos avise e se tenha alguma outra dúvida estamos a disposição.

Um grande abraço
