### ISSUE TITLE
Area de cliente

### ISSUE THREAD

**Issue by kalukramer** [TecSecret/TSDC-Assistencia#7]
Problemas detetados, apartir do opera (bronwser):
Não imprime OS, fica em branco.
No admon, no cadastro do cliente aparece um erro no campo do código (password) mesmo sem preencher nenhum campo...

https://demotsdc.tecsecret.com.br/index.php/conecte/
User: teste@gmail.com
pass: teste

**Comment by TecSecret** [comment]
Boa tarde @kalukramer 

Obrigado por nos reportar o problema da os em branco pelo Opera. Vamos analisar o que possa estar ocorrendo e nos próximos dias lançaremos um commit com a correção.

Teve algumas correções na release 1.1 update 1 referente a área do cliente, solicito que realize o update para a mesma ou faça pelo branch master do repo.

Um grande abraço

**Comment by Fcodapaz** [comment]
Boa noite, no chrome tbm aparece o mesmo erro no campo código. E também não imprimi nenhum relatórios.

**Comment by TecSecret** [comment]
Boa noite @Fcodapaz e @kalukramer já estamos trabalhando nas correções desses problemas.
Em breve terá um commit com a solução.

**Comment by feralton** [comment]
Ola pessoal bom dia. Primeiramente gostaria de agradecer a iniciativa da equipe TecSectret que "deu vida" a esse projeto que estava a muito tempo parado, e em uma semana de dev o sistema é outro, com muito mais funcionalidade e o melhor de tudo, agora com uma equipe desenvolvendo. 
Eu não sei se seria aqui o melhor lugar para eu postar essa sugestão e caso esteja errado, sintam-se no dever de me corrigir. Seria na área do cliente, eu acharia mais interessante quando o cliente acessar a sua área, as informações de Minha Conta fosse apenas exibida para o cliente, sem que o mesmo tenha permissão para edição das informações, forcando o mesmo a entrar em contato com a assistencia técnica para qualquer tipo de atualização. O que vocês acham?
Muito obrigado a todos.

**Comment by TecSecret** [comment]
Boa tarde @feralton  

Primeiramente obrigado  por visitar e estar contente com o projeto. Nós da TecSecret juntamente com a @dcweb-solutions  temos com o objetivo com as sugestões de vocês e tudo transformar ou deixar o sistema mais próximo possível da realidade. 

Para debater sobre este assunto que você mencionou sugiro que abra um novo issues para podermos debater melhor e não misturar os assuntos.
Mas de qualquer forma a sua solicitação será analisada.

A TecSecret e a @dcweb-solutions  agradece a sua sugestão.

**Comment by TecSecret** [comment]
Boa noite a todos.:
 TecSecret e a @dcweb-solutions estão disponibilizando aqui uma atualização para corrigir o problema do Código e também da OS em branco.

Realizem o update do seu sistema e caso o problema persista nos reportem.

Agradecemos a colaboração. Caso for necessário reabra  Issues.
