### ISSUE TITLE
problema com ficheiro config.php ..

### ISSUE THREAD

**Issue by kalukramer** [TecSecret/TSDC-Assistencia#8]
depois de algum tempo a tentar descobrir porque dava o erro e não dava a pagina de login, verifiquei que ao alterar estas duas linhas no config.php o programa passou a mostara a janela de login
allowed_domains = array('os.dev');
$default_domain  = 'os.dev';

para

allowed_domains = array('');
$default_domain  = '';

Agora não faz login...
podem ajudar?

**Comment by TecSecret** [comment]
Boa tarde @kalukramer ,

Você fez conforme o procedimento de instalação: https://github.com/TecSecret/TSDC-Assistencia/wiki/Instala%C3%A7%C3%A3o

Pois este erro é devido a instalação errada.

Após realizar a instalação conforme o procedimento nos reporte o resultado.

**Comment by kalukramer** [comment]
boas, já segui a indicação e dá um erro semelhante e aparece o seguite na parra de url. http://lizbit.pt/os3lizbit.pt/login

as linhas ficaram assim: 
$allowed_domains = array('lizbit.pt');
$default_domain  = 'lizbit.pt';

**Comment by TecSecret** [comment]
boa tarde @kalukramer 

Estamos analisando o que pode ser, pois este problema aparentemente aparece somente em hospedagens com Cpanel,.

Em breve postaremos um update no git com a correção ou na wiki caso for um procedimento a ser feito..

Abraços

**Comment by SmithRider** [comment]
Perfeito! Instalei novamente após a atualização e abriu normal agora.
Obrigado!
