### ISSUE TITLE
galera estou recebendo estes erros pos instalacao 

### ISSUE THREAD

**Issue by turbonetlink** [TecSecret/TSDC-Assistencia#9]
galera estou recebendo estes erros pos instalacao 
imagen em anexo
![erro de php](https://cloud.githubusercontent.com/assets/12984495/24337269/9d04a77c-1271-11e7-88e6-cba438d4a4d7.jpg)

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/microse1/public_html/os/application/language/portuguese-br/tsdc_lang.php:1)

Filename: helpers/url_helper.php

Line Number: 564

A PHP Error was encountered

Severity: Core Warning

Message: Module 'ionCube Loader' already loaded

Filename: Unknown

Line Number: 0

**Comment by TecSecret** [comment]
Boa noite @turbonetlink ,

Em que momento este erro acontece?? Você seguiu nosso procedimento de instalação??

Um detalhe é que nós não usamos Ioncube. 

Você alterou corretamente o arquivo config.php e o database.php, importou o banco de dados??

Veja se o php que você esteja usando é o 7.0.

Estamos a disposição para qualquer outra dúvida

**Comment by turbonetlink** [comment]
foi bem depois de instalar o resto foi seguido a risca vou fazer novamente a instalacao

**Comment by TecSecret** [comment]
Bom doa @turbonetlink ,

Ok, qualquer dúvida estamos a disposição.

**Comment by Fcodapaz** [comment]
@turbonetlink  descobriu qual era o erro?

**Comment by Fcodapaz** [comment]
Bom dia.
Descobrir o erro, era só um espaço na primeira linha depois da tag php.
também tive erros nas classes da pasta controller e models, e tive que renomear todas as classes com a primeira letra maiúscula. Lembrando que esses erros só aconteceram no ubuntu, no windows rodou normal. Se acontecer com alguém tentem fazer isso.

**Comment by TecSecret** [comment]
Boa tarde @Fcodapaz,

Realmente não sei porque aqui no repo as classes não aparecem renomeadas e no nosso repo de dev aparecem, não tínhamos percebido isso.

Obrigado por ter percebido isso, estamos realizando a renomeação das classes agora aqui no repo.

Abraços

**Comment by turbonetlink** [comment]
tem com voce mandar o arquivo para fazer a subistituicao ?

**Comment by leonidasfsilva** [comment]
Olá @TecSecret 
Poderia me ajudar?
Ainda estou com o mesmo problema citado neste tópico: 

**A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/clube861/public_html/mapos/v2/application/language/portuguese-br/tsdc_lang.php:1)

Filename: helpers/url_helper.php

Line Number: 561**

Já exclui todo o diretório e banco de dados na minha hospedagem e refiz a instalação, porém
continuo recebendo este erro.
Minha hospedagem é HostGator.

Poderia me dar uma força? Preciso muito deste sistema pra me organizar nos freelas. rs

Desde já agradeço o belo trabalho de continuar o projeto.
Grande abraço!

**Comment by leonidasfsilva** [comment]
Acabei de solucionar pesquisando nos fóruns do stackoverflow.
Pra quem ainda está com o mesmo problema, a solução que deu certo pra mim foi:

Abra o arquivo <b>tsdc_lang.php</b> no diretório 
...\www\mapos\application\language\portuguese-br
e mude a codificação do arquivo para <b>UTF-8 (sem BOM)</b>

Eu aqui usei o Notepad++ juntamente com o FileZilla para fazer a correção.

Espero que ajude.
